package net.arna.jcraft.datagen.providers.resources;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import net.arna.jcraft.JCraft;
import net.arna.jcraft.api.JRegistries;
import net.arna.jcraft.api.attack.MoveMap;
import net.arna.jcraft.api.attack.MoveSetManager;
import net.arna.jcraft.api.attack.moves.AbstractMove;
import net.arna.jcraft.api.spec.SpecData;
import net.arna.jcraft.api.stand.StandData;
import net.arna.jcraft.api.stand.StandInfo;
import net.arna.jcraft.datagen.providers.data.JSpecDataProvider;
import net.arna.jcraft.datagen.providers.data.JStandDataProvider;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.ComponentContents;
import net.minecraft.network.chat.contents.LiteralContents;
import net.minecraft.network.chat.contents.TranslatableContents;
import net.minecraft.resources.ResourceLocation;
import org.jetbrains.annotations.NotNull;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.function.BiConsumer;
import java.util.stream.Collectors;

public class JLangProvider implements DataProvider {
    private final Path langFile;
    private final Map<String, String> lang;

    // Cache provider data to avoid repeated expensive instantiation
    private final Map<ResourceLocation, StandData> standDataMap;
    private final Map<ResourceLocation, SpecData> specDataMap;

    public JLangProvider(FabricDataOutput dataOutput) {
        // Initialize provider data maps once to avoid repeated expensive instantiation
        this.standDataMap = new JStandDataProvider(dataOutput).getDataMap();
        this.specDataMap = new JSpecDataProvider(dataOutput).getDataMap();

        String resourcesDir = System.getProperty("jcraft.datagen.resources-source");
        if (resourcesDir == null || resourcesDir.isBlank()) {
            throw new IllegalArgumentException("The 'jcraft.datagen.resources-source' system property must be set to the resources directory.");
        }

        // Languages are not loaded in datagen, so we read the language file directly from the resources directory.
        langFile = Path.of(resourcesDir, "assets", JCraft.MOD_ID, "lang", "en_us.json");
        try (BufferedReader reader = Files.newBufferedReader(langFile)) {
            JsonObject langObj = new Gson().fromJson(reader, JsonObject.class);
            lang = langObj.entrySet().stream()
                    .map(entry -> Map.entry(entry.getKey(), entry.getValue().getAsString()))
                    .filter(entry -> filterGeneratedKeys(entry.getKey())) // Filter out generated keys
                    .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue, (s1, s2) -> s1, LinkedHashMap::new));
        } catch (IOException e) {
            throw new RuntimeException("Failed to read language file: " + langFile, e);
        }
    }

    private boolean filterGeneratedKeys(String key) {
        // Filter out keys that are generated by this class, such as those starting with "move."
        if (key.startsWith("entity." + JCraft.MOD_ID)) {
            String standKey = standDataMap.values().stream()
                    .map(StandData::getInfo)
                    .map(StandInfo::getNameKey)
                    .filter(key::startsWith)
                    .findAny()
                    .orElse(null);
            if (standKey != null) {
                return !key.endsWith(".freeSpace") && !key.substring(0, key.length() - 1).endsWith(".skin");
            }
        }

        if (key.startsWith("spec." + JCraft.MOD_ID)) {
            String specKey = specDataMap.values().stream()
                    .map(SpecData::getNameKey)
                    .filter(key::startsWith)
                    .findAny()
                    .orElse(null);
            if (specKey != null) {
                return !key.endsWith(".desc") && !key.endsWith(".details");
            }
        }

        return !key.startsWith("move.");
    }

    @Override
    public @NotNull String getName() {
        return "Moveset and Data Language";
    }

    @Override
    public @NotNull CompletableFuture<?> run(@NotNull CachedOutput output) {
        Map<String, String> newLang = new LinkedHashMap<>(lang);
        BiConsumer<String, String> builder = (key, value) -> {
            if (value != null && !value.isBlank() && newLang.put(key, value) != null) {
                throw new IllegalArgumentException("Duplicate or invalid key found in language file: " + key);
            }
        };

        generateTranslations(builder);

        // Write output
        JsonObject obj = new JsonObject();
        newLang.forEach(obj::addProperty);

        return DataProvider.saveStable(output, obj, langFile);
    }

    private void generateTranslations(BiConsumer<String, String> builder) {
        generateMoveSetTranslations(builder);
        generateStandDataTranslations(builder);
        generateSpecDataTranslations(builder);
    }

    private void generateMoveSetTranslations(BiConsumer<String, String> builder) {
        Set<ResourceLocation> ids = new HashSet<>(JRegistries.STAND_TYPE_REGISTRY.getIds());
        ids.addAll(JRegistries.SPEC_TYPE_REGISTRY.getIds());

        Set<String> keys = new HashSet<>();

        for (ResourceLocation type : ids) {
            MoveSetManager.get(type).forEach((id, moveSet) -> {
                String msBaseKey = String.format("move.%s.%s", type.toLanguageKey(), moveSet.getName());
                MoveMap<?, ?> moveMap = moveSet.save();
                for (AbstractMove<?, ?> move : moveMap.asMovesList()) {
                    String key = generateKey(move.getName());
                    if (key == null) {
                        continue; // Skip if the key cannot be generated, likely already translated.
                    }

                    String baseKey = String.join(".", msBaseKey, key);
                    if (move.isFollowup()) baseKey += ".followup";
                    else if (move.isCrouchingVariant()) baseKey += ".cr";
                    else if (move.isAerialVariant()) baseKey += ".air";

                    if (!keys.add(baseKey)) throw new IllegalArgumentException(String.format(
                            "Move %s from moveset %s of type %s resolves to a duplicate key: %s",
                            toString(move.getName()), moveSet.getName(), type, baseKey));

                    addIfLiteral(move.getName(), baseKey + ".name", builder);
                    addIfLiteral(move.getDescription(), baseKey + ".description", builder);
                }
            });
        }
    }

    private void generateStandDataTranslations(BiConsumer<String, String> builder) {
        for (Map.Entry<ResourceLocation, StandData> entry : standDataMap.entrySet()) {
            String[] parts = entry.getKey().getPath().split("_");
            String variant = JRegistries.STAND_TYPE_REGISTRY.contains(entry.getKey()) ? null : parts[parts.length - 1];

            StandData data = entry.getValue();
            StandInfo info = data.getInfo();
            String baseKey = info.getNameKey() + (variant == null ? "" : "." + variant) + ".info";

            addIfLiteral(info.getFreeSpace(), baseKey + ".freeSpace", builder);
            for (int i = 0; i < info.getSkinNames().size(); i++) {
                Component skin = info.getSkinNames().get(i);
                addIfLiteral(skin, baseKey + ".skin" + (i + 1), builder);
            }
        }
    }

    private void generateSpecDataTranslations(BiConsumer<String, String> builder) {
        for (SpecData data : specDataMap.values()) {
            String baseKey = data.getNameKey() + ".info";

            addIfLiteral(data.getDescription(), baseKey + ".desc", builder);
            addIfLiteral(data.getDetails(), baseKey + ".details", builder);
        }
    }

    private static void addIfLiteral(Component component, String key, BiConsumer<String, String> builder) {
        if (component.getContents() instanceof LiteralContents literal) {
            builder.accept(key, literal.text());
        }
    }

    private String generateKey(Component comp) {
        ComponentContents contents = comp.getContents();
        String name = contents instanceof LiteralContents literal ? literal.text() :
                contents instanceof TranslatableContents translatable ? String.format(translate(translatable)) : null;
        if (name == null || name.isBlank()) {
            return null; // Skip if the name is null or empty
        }

        String key = name
                .trim() // Trim leading and trailing whitespace
                .replaceAll("[^a-zA-Z0-9 ]", "") // Remove non-alphanumeric characters
                .replace(' ', '_') // Replace spaces with underscores
                .toLowerCase(Locale.ROOT); // Convert to lowercase
        return key.isEmpty() ? null : key;
    }

    private String toString(Component comp) {
        ComponentContents contents = comp.getContents();
        if (contents instanceof LiteralContents literal) {
            return literal.text();
        } else if (contents instanceof TranslatableContents translatable) {
            return translate(translatable);
        }

        return null; // Return null for unsupported contents
    }

    private String translate(TranslatableContents translatable) {
        return String.format(lang.getOrDefault(translatable.getKey(), translatable.getKey()), translatable.getArgs());
    }
}
